### ISSUE TITLE
Why IE11 and Microsoft Edge browser can`t download？ 

### ISSUE THREAD

**Issue by YPKSEU139** [openkm/document-management-system#155]
<img width="728" alt="_20181031151506" src="https://user-images.githubusercontent.com/7539369/47771847-c7c37400-dd1f-11e8-94b4-8c90acaf3e94.png">

Can`t download files ，it`s messy code.

Is that my problem or is there any other solution?   Thank you for your answer ，I love OpenKM

这是我的问题，还是说有其他解决方案？

**Comment by YPKSEU139** [comment]
IE和 Edge浏览器，下载的都是乱码。

**Comment by YPKSEU139** [comment]
IE and Edge browsers, all downloaded files are garbled.

**Comment by darkman97i** [comment]
I prefer to discuss this issue from forum.openkm.com because might be this is not a bug, quite strange you are the first person during several years who cannot download files from IE.

In the post, please share with us, the OpenKM version, what OS you have it running. If the error also happens with European charset. Will be better for us screenshots with English browser.
