### ISSUE TITLE
Install error SunCertPathBuilderException

### ISSUE THREAD

**Issue by hugo53** [openkm/document-management-system#16]
Hi @darkman97i ,
I tried to install OpenKM but catch the error when download Tomcat
```ERROR: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path ```

See more details below

```
MacOS 10.12.5

sudo java -jar OKMInstaller.jar
Unknown platform: 0.0.0 (build: 0)
Local host: PC-5.local
Java version: 1.8.0_31
Free disk size: 14.3 GB
RAM size: 8.0 GB
CPU cores: 4
Current directory: /Users/username/Downloads

Database [h2]: mysql
Database host [localhost]: 
Database name [okmdb]: 
Database user [openkm]: 
Database password [EzViiI0wTx52]: 
---------------------------
- Database: mysql
- Database host: localhost
- Database name: okmdb
- Database user: openkm
- Database password: EzViiI0wTx52
- Install version: 6.3.4
---------------------------
Start install process? [y/N]: y

- Downloading Tomcat: 7.0.61
ERROR: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
I tried to import manually Tomcat certificate into jre/lib/security/cacerts (export cert from this link https://tomcat.apache.org/download-70.cgi) but it didn't work. Please take a look. Thank you!

**Comment by darkman97i** [comment]
Installer is not going right under MacOS. It has not been optimized for it and I do not suggest installing OpenKM into MacOS computer. 

Althought you can get running into is not a good idea, for several reasons:
- OpenKM need thirdparty software that might not be easy to get installed into MacOS
- There's an indexing tool in MacOS ( I do not remember the name ) what you should disable, otherwise you will get a poor performance because this tools will be trying to indexing binary files controlled by OpenKM ( not a good idea ).
- We suggest installing OpenKM as stand alone service into a Server ( better linux distribution for better I/O support ).

Anyway if you want to go ahead you should, download our Tomcat and OpenKM.war file:
- https://sourceforge.net/projects/openkm/files/common/Tomcat-7.0.61.zip/download
- https://sourceforge.net/projects/openkm/files/6.3.4/OpenKM-6.3.4.zip/download

Finally, follow equivalent linux steps in your computer ( try following the steps described here https://docs.openkm.com/kcenter/view/okm-6.3-com/installing-on-ubuntu-and-debian.html )

**Comment by hugo53** [comment]
@darkman97i Thanks for your suppport. I will try those things you've suggested!

**Comment by andresm1991** [comment]
Hello, I have the same problem on the ubuntu server and I can't find the solution, thanks in advance

**Comment by darkman97i** [comment]
What version of JAVA are you using?

**Comment by darkman97i** [comment]
I think the problem maybe is this old tomcat version not works with JDK 1.8 but the installed should install a tomcat 8.x

I think you are using and old installer because it si trying to install and old Tomcat version 7.0.61 and should installing version 8.X -> ensure you download the latest jar installer at https://sourceforge.net/projects/openkm/files/common/OKMInstaller.jar/download

Another matter is the OS version: MacOS 10.12.5 we do not recommend installed into a MACOS if the problem persist should looking in google for this issue, because it seems the certificates has not been installed by the JDK in your server

**Comment by darkman97i** [comment]
Hi @andresm1991 Please open a new issue, because this issues was started by other user talking about Mac OS and seems you have Ubuntu -> this sure will be a different matter
