### ISSUE TITLE
PathNotFoundException: /okm:trash

### ISSUE THREAD

**Issue by pucojazu** [openkm/document-management-system#211]
Hi,

i have a technical user who does not have the normal user role (ROLE_USER) because he is used for automatic imports.
That's working so far, the user can upload documents via the REST API.

But I would also like to do a simple login check without uploading anything.
I tried to call /auth/login, but it gives me this Exception:
`RepositoryException: PathNotFoundException: 3b33f718-c150-4fd5-b510-846d4b3df803 : /okm:trash`

It seems I can not edit the permissions of /okm:trash.

How can I fix this?
Or is there any other simple way to check that the login is working?

**Comment by darkman97i** [comment]
- Users must be members of ROLE_ADMIN or ROLE_USER ( this is mandatory )
- If you are only using webservices it is a good practice the first time execute the login method ( from Auth ), because the execution of login method from REST will create users folders ( in trash, personal, etc... ), that happens automaticlly when you login from UI, but if your users never use standard UI then will not be created ( then it is necessary at least one time, execute the login method )

When you execute login you need grants to create these folders, that's the reason why you are getting this error. Hope the explanation will help you.

**Comment by pucojazu** [comment]
Thanks for the explanation!

My technical user is not a member of ROLE_ADMIN or ROLE_USER, but only of a newly created role, which has permissions to only one folder which is used for my document import. I don't want this  user to have access to anything else or any personal folders.
Login from the UI fails for this user with the same PathNotFoundException as mentioned above.

I think it would be better if access or creation of the personal folders was not be attempted during login if the user does not have the necessary rights. Because now the login fails even though my user really has access to the system (he can create documents in the granted folder).

But for my use case it does not matter anymore, I'm now checking the access via /folder/isValid instead of /auth/login. That makes even more sense in my case. :)

**Comment by darkman97i** [comment]
Be a member of ROLE_USER or ROLE_ADMIN is mandatory for all the users. Because these roles are used for accessing the application. Until you promote the user to ROLE_ADMIN you will have the error.

**Comment by pucojazu** [comment]
Ok, not a problem, as long as the access with basic auth works anyways.
I'll close this issue then.
