### ISSUE TITLE
use openkm for own Java project

### ISSUE THREAD

**Issue by 321drago** [openkm/document-management-system#212]
Hi,
i want to use some openkm features for my own java-project. I want to import pdf-documents with my software and show all documents with a filter by documentname.

Is there a final openkm.jar or how can i implement my issue.

Best regards

**Comment by darkman97i** [comment]
The easiest maybe using OpenKM as is, an integrate OpenKM with your application using the OpenKM REST API. There's an SDK what has been thought for it ( take a look here https://docs.openkm.com/kcenter/view/sdk4j-1.2/ ), the idea is having a man-in-the-middle a single OpenKM user used from your application across the webservices API.

you can upload documents https://docs.openkm.com/kcenter/view/sdk4j-1.2/document-samples.html#createDocumentSimple

or make searches https://docs.openkm.com/kcenter/view/sdk4j-1.2/search-samples.html#findByName

I think that will be better than collect pieces of code, at the end you will benefits of the current and future improvements and bugs corrections.

**Comment by 321drago** [comment]
Thank you very much.
I found this documentation about the sdk, but where can i download the library. In the sample they import com.openkm.sdk4j?

**Comment by darkman97i** [comment]
The samples in the documentation are for a maven project or a jar file project
https://docs.openkm.com/kcenter/view/sdk4j-1.2/sample-client.html

From here you can download the jar file http://maven.openkm.com/com/openkm/sdk4j/1.2/ , but because the project require thirdparty libraries I suggest build the jar file with depencies for it there's a github project https://github.com/openkm/sdk4j-with-dependences

**Comment by 321drago** [comment]
I tried to build the jar, but get a exception: ReasonPhrase:HTTPS Required

**Comment by darkman97i** [comment]
If the issue happens in the other probject please add the issue there

**Comment by 321drago** [comment]
Problem solved
