### ISSUE TITLE
Flash Preview

### ISSUE THREAD

**Issue by biglioncoding** [openkm/document-management-system#25]
As most developers and power users are aware of, flash is soon (if not now) obsolete.  It is going to be EOL in 2020 and I suspect mainstream browsers may totally cut flash support officially.

I think the OpenKM development team may consider html5 solution and replace flash preview.

Thanks.

**Comment by darkman97i** [comment]
We are using flexpaper ( now named flowpaper ) for previewing PDF. In professional version we do not have problems, because the professional license of flowpaper works with HTML5, the issue comes with community license ( application what comes with some limitation ) what only works with flash player. Some user suggested us another tool for previewing PDF with HTML5.

I'm totally agree with you, like JAVA applets seems this kind of technology is obsolete and should move in some direction to solve it.

You are welcome to collaborate on it or suggest some alternative for it. If you want to work with the source code we can guide you on the classes that should be changed ( might be not much dificulties doing it).

**Comment by darkman97i** [comment]
One alternative is http://viewerjs.org/ might looking for more.

**Comment by monkiki** [comment]
If anyonw knows another Open Source alternative, please tell us.

**Comment by monkiki** [comment]
Fix commited to 6.3-DEV branch.
