### ISSUE TITLE
the document

### ISSUE THREAD

**Issue by belle561** [openkm/document-management-system#267]
hi
we have encrypted files in datastore,
in which class you have to modify to decrypt the files to be used in openkm (if you perceived, search ....)

**Comment by darkman97i** [comment]
Depending what will be your expected behaviour should modify a lot of classes. In `FsDataStore.class` you have he method `read`
https://github.com/openkm/document-management-system/blob/master/src/main/java/com/openkm/module/db/stuff/FsDataStore.java

After applying this change you will be able to download decrypt documents. But still with have a lot fo features not working like:
preview, search engine, thumbnail if you want to get these feature working should look where is used the method `resolveFile` in the  `FsDataStore.class` because sometime in the application we use directly the path in the file system.

Will be good idea to have a genera configuration parameter in `Config.java` class https://github.com/openkm/document-management-system/blob/master/src/main/java/com/openkm/core/Config.java to mark when the encryption is enabled or not. That can be used to split your code from current in almost sections of the core.

**Comment by belle561** [comment]
hi,
I do  decryption file when importing the file into datastore.
what are the classes that import the files that are in datastore?

**Comment by darkman97i** [comment]
In case you are using eclipse, you should use references:

![Selección_020](https://user-images.githubusercontent.com/958703/100351134-3cdf0180-2feb-11eb-915f-a04815b6872b.png)

![Menú_019](https://user-images.githubusercontent.com/958703/100351135-3d779800-2feb-11eb-89e3-5ef9df9e9df0.png)

**Comment by darkman97i** [comment]
Because long inactivity I will close the issue. If you have any question please open a new ticket.
