### ISSUE TITLE
Huge amount of tmp-files in tomcat/temp 

### ISSUE THREAD

**Issue by zengsentry** [openkm/document-management-system#271]
Hello team , still meet Huge amount of tmp-files issue in Latest release v6.3.9

Environment：
OS: CentOS Linux 7.7.1908 (Core)　　
tomcat version is **tomcat-8.5.34**
OpenKm Version:  **Latest release v6.3.9**
I had created a issues  #202  in last year
[ISSUE #202](https://github.com/openkm/document-management-system/issues/202#issue-507739937)

**Comment by zengsentry** [comment]
Dear  Team
  any update for this issue?

**Comment by darkman97i** [comment]
In linux should not happens do:
1- upgrade to 6.3.10 ( latest )
2- also try to update tomcat to the latest version provided by openkm ( tomcat-8.5.58 -> http://download.openkm.com/okm/tomcat-8.5.57.zip ) 

* Before trying to replace tomcat version please do a full backup
* If it is not clear the files what must be copied between the tomcats or modified tell us.

**Comment by zengsentry** [comment]
Dear team 
   Thank you for you update,
   I'm not clear the files what must be copied between the tomcats or modified. tomcat-8.5.57 seems miss many files. I'm can not start  tomcat successfully now.

**Comment by zengsentry** [comment]
I have observed that We can find the final file structure and directory  under tomcat/temp  folder when  huge amount of temp-files in tomcat/temp  happened.

Environment：
OS: CentOS Linux 7.7.1908 (Core)　　
tomcat version is tomcat-8.5.34
OpenKm Version: Latest release v6.3.10 ( latest )
you can refer below 

![20210131154347](https://user-images.githubusercontent.com/17687248/106379201-4585f680-63e5-11eb-980b-ac169241412e.png)

![20210131154418](https://user-images.githubusercontent.com/17687248/106379207-4dde3180-63e5-11eb-84c8-5fcc02941876.png)

![20210131154238](https://user-images.githubusercontent.com/17687248/106379216-533b7c00-63e5-11eb-9588-31ea744150a2.png)

**Comment by darkman97i** [comment]
Can you check the file type:
file "name of the file"

**Comment by zengsentry** [comment]
Dear team
 this bug don't  reproduce agian after increase hard disk space

**Comment by darkman97i** [comment]
It means in the temp folder do not increase the number of files exponentially or because you have more disk space now is not a problem?

This huge - 6GB -  tmp folders it seems like some user tried to download huge folder -> in this scenario application create large amount of data in a temporary folder to create zip file.

Maybe should restrict user who can do these actions from profiles and also in the activity log should be information about which one has executed it ( in the configuration parameter activity.log.actions  I think we do not have an event for it purpose -> https://docs.openkm.com/kcenter/view/okm-6.3-com/activity-log.html ).

**Comment by darkman97i** [comment]
Because long time without answering I will close the issue. If you have any question about this matter open a new issue.
