### ISSUE TITLE
Document managing plugin and API

### ISSUE THREAD

**Issue by deep2468** [openkm/document-management-system#283]
plugin request
1. Edit documents directly from openkm and
2. Microsoft office plugin for Access.

API request
provide API to create file from template

**Comment by darkman97i** [comment]
* About edit document directly from OpenKM is not a plugin will be integration, should be chosen some online editor like Collabora Online Office, Online Office, Libre Office Online and then integrate.
* About Microsoft Access addin do not have much difficulties to implement it. But in past and now we think do not have much sense to keep access documents in the DMS and then edit. Usually, the database files should be in a server to be used by the users ... this is quite strange behavior ( keep in DMS if it is not for backup purposes ), that's why we have not implemented because do not see advantatges or users what will use it.

In this issue, we will attend the request to implement **create from template** feature ( in the future please open a single issue for each topic, do not merge several questions into the same ).

**Comment by deep2468** [comment]
@darkman97i  I am grateful for your support and sorry for creating multiple issue in single topic I will take care next time.
- I will try online office integration for editing document directly.

- You are correct about Access where it use on daily basis. **In our case** we have few Access templates. Access file is updating once in a month to import monthly finalized data for generating various monthly and year to date reports that also help in storing data for long term. Accordingly I was wondering if is it possible to create Access addin then that will be beneficial to handle Access file in more better way.
 
-  Thank you for accepting creating file from template API implementation request.

**Comment by darkman97i** [comment]
For us currently do not have much interest to add Ms Office addin feature in the Access, when seeing general-purpose feature we do, but the efforts to do and maintaining do not compensate. Maybe a solution for you will be using hot folder. User mapping a folder in openkm and with drag & drop update the file https://www.youtube.com/watch?v=zLRjkNrSp40

**Comment by deep2468** [comment]
I appreciate your and your teams efforts towards open source software.
Thank you so much.
