### ISSUE TITLE
Blank page after login and Error getting translations

### ISSUE THREAD

**Issue by rickywu** [openkm/document-management-system#93]
Error getting translations: No row with the given identifier exists: [com.openkm.dao.bean.Language#zh-CN]

I added default.lang=en-GB got the same problem
I have to edit system language as English then can login

**Comment by darkman97i** [comment]
Seems you have registered the Chinese language? I suspect is not a bug, it is another kind of issue but:
1- stop openkm
2- delete all files into logs folder
3- start openkm
4- try to login
5- share with us the catalina.log file

**Comment by rickywu** [comment]
[openkm.log](https://github.com/openkm/document-management-system/files/2309148/openkm.log)

I use docker run openkm

**Comment by darkman97i** [comment]
The error seems clear is trying to retrieve language zh-CN what does not exist in the database. Here you have two solutions, register it or change default.lang what I suspect is not en-GB otherwise I do not understanding why is getting it.

Might be the easies is:
1- download https://docs.openkm.com/kcenter/Download?node=b14b89ef-d7bd-4706-92c4-41eeef7bb2e6&inline=true
2- login into localhost:8080/OpenKM/admin with okmAdmin user
3- go to database query, choose JDBC, copy the content of the file download and execute it.
4- restart the application
